### ISSUE TITLE
The example configuration don't work when dealing with submodules

### ISSUE THREAD

**Issue by bric3** [chrimaeon/gradle-licenses-plugin#14]
Typically I followed the readme

```kotlin
licenses {
    additionalProjects = setOf(":modules:a", ":modules:b")
    reports {
        text {
            enabled = true
            destination = file("$buildDir/reports/licenses.txt")
        }
    }
}
```

But the `licenseReport` task don't use the additionalProjects value from the license block. So it doesn't walk through the sub-project's dependencies. And produces no report.

Instead actually had to move my configuration to the `licenseReport` task to make this work.
Note even the `reports` block has to be configured in the task.

```
tasks.licenseReport {
    additionalProjects = setOf(":modules:a", ":modules:b")
    reports {
        text {
            enabled = true
            destination = file("$buildDir/reports/licenses.txt")
        }
    }
}
```

**Comment by chrimaeon** [comment]
`additionalProjects = setOf(":modules:a", ":modules:b")` in the licenses extension does not work. there is no direct setter.
you should use the `additionalProjects(vararg modules: String)` or `additionalProjects(modules: Collection<String>)` methods
