### ISSUE TITLE
couldn't get outputtype to text format

### ISSUE THREAD

**Issue by naveenvenkannagari** [chrimaeon/gradle-licenses-plugin#3]
When i tried using 
licenses {
        outputType = OutputType.TEXT
}

getting following error 
Could not get unknown property 'OutputType' for object of type com.cmgapps.license.LicensesExtension.

**Comment by drostowsky-tmobile** [comment]
Same issue for me as well.

**Comment by drostowsky-tmobile** [comment]
This works for me...

```
    licenses {
        outputType = com.cmgapps.license.OutputType.TEXT
    }
```

**Comment by serhuz** [comment]
`outputType = OutputType.TEXT` works for me when I place `import com.cmgapps.license.OutputType` in my `build.gradle` script

**Comment by chrimaeon** [comment]
yes, `OutputType` needs to be imported
