### ISSUE TITLE
report generator does nothing - caching disabled

### ISSUE THREAD

**Issue by stealthrabbi** [chrimaeon/gradle-licenses-plugin#4]
U> Task :licenseReport
Task :licenseReport in subproj1 Starting
Caching disabled for task ':licenseReport' because:
  Caching has not been enabled for the task
Task ':licenseReport' is not up-to-date because:
  Task.upToDateWhen is false.
Task :licenseReport in subproj1 Finished
:licenseReport (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.035 secs.
nless you run with --info to see details, the plugin does nothing if caching is not enabled

**Comment by stealthrabbi** [comment]
enabling caching via gradle.properties has no effect.

**Comment by chrimaeon** [comment]
Caching is disabled for this task to always run. there is no way the plugin can determine if the required files changed.

Can you send the project setup?
